ECHO OFF
CLS
CALL %APP_DATA_HOME%\envVars.bat
SET JAVA_HOME=%JAVA_HOME%
SET PATH=%RPAS_HOME%\bin;%RPAS_HOME%\applib;%RPAS_HOME%\lib;%RIDE_HOME%\bin;%RIDE_HOME%\lib;%PATH%
ECHO RPAS_HOME=%RPAS_HOME%
ECHO RIDE_HOME=%RIDE_HOME%
ECHO PATH=%PATH%
START %RIDE_HOME%\bin\ConfigTools.exe
